name: Diplobank
main: thatsean.diplobank.Main
version: '0.1'
description: A Paper plugin for Diplobank.
api-version: '1.19'
dependencies:
  server:
    Vault:
      required: true
      load: BEFORE
# No commands section - commands are registered programmatically