name: Diplobank
main: thatsean.diplobank.Main
version: 0.1
description: A plugin for managing Diplobank features.
authors:
  - Sean G
  - Diplomacy Craft Team
api-version: 1.19
depend: [Vault]
permissions:
  mcurbank.admin:
    description: Allows access to admin commands.
    default: op
  mcurbank.user:
    description: Allows access to user commands.
    default: true
# No commands section - commands are registered programmatically